{
  description = "Python Development Environment";

  # USAGE:
  # 1. direnv allow   (or: nix develop)
  # 2. pip install -r requirements.txt
  # 3. After adding packages: pip freeze > requirements.txt

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { nixpkgs, ... }:
    let
      system = "x86_64-linux";  # x86_64-linux | aarch64-linux | x86_64-darwin | aarch64-darwin
      pkgs = nixpkgs.legacyPackages.${system};
      lib = pkgs.lib;

      # System libraries that compiled pip wheels need at runtime (numpy, scipy, etc.).
      # Add pkgs entries here as your project requires — e.g. openssl, zlib, libffi.
      runtimeLibs = with pkgs; [
        stdenv.cc.cc.lib  # libstdc++/libgcc_s — needed by virtually every C-extension wheel
      ];

      libPath = lib.makeLibraryPath runtimeLibs;

      # IDEs launch .venv/bin/python directly without the dev-shell environment, so
      # LD_LIBRARY_PATH is empty and C-extension imports fail. Setting LD_LIBRARY_PATH
      # from sitecustomize.py is too late (glibc caches the dlopen search path at
      # startup), so we ctypes.CDLL the libs with RTLD_GLOBAL instead — subsequent
      # dlopen calls resolve their SONAMEs from the already-loaded set.
      sitecustomize = pkgs.writeText "sitecustomize.py" ''
        # Auto-generated by flake.nix — do not edit, regenerated on every nix develop.
        import ctypes, glob, os

        _LIB_DIRS = [
        ${lib.concatMapStringsSep "\n" (d: "    ${"\""}${d}${"\""},") (lib.splitString ":" libPath)}
        ]

        # Sanitizer libs (libasan/libtsan/libubsan) are excluded — they must be loaded
        # first via LD_PRELOAD and break if dlopened late.
        _ALLOWED = (
            'libstdc++.so.', 'libgcc_s.so.',
            'libssl.so.', 'libcrypto.so.',
            'libz.so.', 'libbz2.so.', 'liblzma.so.',
            'libffi.so.', 'libsqlite3.so.',
            'libreadline.so.', 'libncursesw.so.',
        )

        for _d in _LIB_DIRS:
            if not os.path.isdir(_d):
                continue
            for _so in glob.glob(os.path.join(_d, 'lib*.so*')):
                if any(os.path.basename(_so).startswith(p) for p in _ALLOWED):
                    try:
                        ctypes.CDLL(_so, mode=ctypes.RTLD_GLOBAL)
                    except OSError:
                        pass
      '';
    in
    {
      devShells.${system}.default = pkgs.mkShell {
        buildInputs = [ pkgs.python311 ] ++ runtimeLibs;

        shellHook = ''
          export LD_LIBRARY_PATH=${libPath}''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

          if [ ! -d .venv ]; then
            echo "Creating Python virtual environment..."
            python3 -m venv .venv
          fi
          source .venv/bin/activate

          # Keep sitecustomize.py current so IDEs that bypass the dev shell still work.
          SITE_PKGS=$(python -c 'import site; print(site.getsitepackages()[0])')
          [ -d "$SITE_PKGS" ] && install -m 644 ${sitecustomize} "$SITE_PKGS/sitecustomize.py"

          if [ ! -f requirements.txt ]; then
            echo "⚠️  No requirements.txt found. After installing packages, run: pip freeze > requirements.txt"
          else
            REQS_HASH=$(sha256sum requirements.txt | cut -d' ' -f1)
            HASH_FILE=".venv/.reqs_hash"
            if [ ! -f "$HASH_FILE" ] || [ "$(cat $HASH_FILE)" != "$REQS_HASH" ]; then
              echo "Installing dependencies..."
              pip install -r requirements.txt --quiet
              echo "$REQS_HASH" > "$HASH_FILE"
            fi
          fi

          echo "✓ Python environment ready  ($(python --version))"
        '';
      };
    };
}
