'use strict';

// Document Viewer: builds a folder-tree nav from docs/manifest.json, renders
// PDFs in an iframe and .docx via the vendored mammoth library, and prints the
// current document. The manifest is generated by scripts/gen-docs-manifest.py.

const nav = document.getElementById('docNav');
const view = document.getElementById('docView');
const current = document.getElementById('docCurrent');
const printBtn = document.getElementById('printBtn');

const DOCS_BASE = '../../docs/';

let activeLink = null;
let currentKind = null; // 'docx' | 'pdf' | null

// Encode each path segment so spaces, parentheses, etc. in filenames resolve.
function docUrl(path) {
  return DOCS_BASE + path.split('/').map(encodeURIComponent).join('/');
}

function el(tag, className, text) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
}

// Label shown to staff: the filename without its extension.
function displayName(node) {
  const suffix = '.' + node.ext;
  return node.name.toLowerCase().endsWith(suffix.toLowerCase())
    ? node.name.slice(0, -suffix.length)
    : node.name;
}

init();

async function init() {
  try {
    const res = await fetch(DOCS_BASE + 'manifest.json', { cache: 'no-cache' });
    if (!res.ok) throw new Error(`manifest ${res.status}`);
    const manifest = await res.json();
    nav.innerHTML = '';
    if (!manifest.tree || manifest.tree.length === 0) {
      nav.appendChild(el('p', 'muted', 'No documents yet.'));
      return;
    }
    nav.appendChild(renderTree(manifest.tree));
  } catch (err) {
    nav.innerHTML = '';
    nav.appendChild(el('p', 'muted',
      'Could not load the document list. Run scripts/gen-docs-manifest.py to build it.'));
  }
}

function renderTree(nodes) {
  const ul = el('ul', 'doc-tree');
  for (const node of nodes) {
    const li = document.createElement('li');
    if (node.type === 'folder') {
      li.className = 'doc-folder';
      li.appendChild(el('div', 'doc-folder-name', node.name));
      li.appendChild(renderTree(node.children));
    } else {
      li.className = 'doc-file';
      const btn = el('button', 'doc-link', displayName(node));
      btn.type = 'button';
      btn.dataset.ext = node.ext;
      btn.addEventListener('click', () => openDoc(node, btn));
      li.appendChild(btn);
    }
    ul.appendChild(li);
  }
  return ul;
}

async function openDoc(node, link) {
  if (activeLink) activeLink.classList.remove('active');
  link.classList.add('active');
  activeLink = link;

  current.textContent = displayName(node);
  printBtn.disabled = true;
  currentKind = null;
  view.classList.remove('showing-pdf');
  view.innerHTML = '';
  view.appendChild(el('p', 'doc-placeholder muted', 'Loading…'));

  try {
    if (node.ext === 'pdf') {
      renderPdf(docUrl(node.path));
      currentKind = 'pdf';
    } else if (node.ext === 'docx') {
      await renderDocx(docUrl(node.path));
      currentKind = 'docx';
    } else {
      view.innerHTML = '';
      view.appendChild(el('p', 'muted', 'This file type can\'t be previewed.'));
      return;
    }
    printBtn.disabled = false;
  } catch (err) {
    view.innerHTML = '';
    view.appendChild(el('p', 'error', 'Could not open this document.'));
  }
}

function renderPdf(url) {
  view.innerHTML = '';
  view.classList.add('showing-pdf');
  const iframe = el('iframe', 'doc-pdf');
  iframe.src = url;
  iframe.title = 'PDF document';
  view.appendChild(iframe);
}

async function renderDocx(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`docx ${res.status}`);
  const arrayBuffer = await res.arrayBuffer();
  // Guard against a stalled conversion so the UI never hangs on "Loading…".
  const result = await withTimeout(
    window.mammoth.convertToHtml({ arrayBuffer }),
    30000,
    'Rendering this document took too long.'
  );
  view.innerHTML = '';
  view.classList.remove('showing-pdf');
  const article = el('article', 'doc-content');
  article.innerHTML = result.value; // mammoth emits sanitized semantic HTML
  view.appendChild(article);
}

function withTimeout(promise, ms, message) {
  let timer;
  const timeout = new Promise((_, reject) => {
    timer = setTimeout(() => reject(new Error(message)), ms);
  });
  return Promise.race([promise, timeout]).finally(() => clearTimeout(timer));
}

// docx renders as HTML we print via the @media print rules; a PDF is printed
// through its own iframe viewer.
printBtn.addEventListener('click', () => {
  if (currentKind === 'pdf') {
    const iframe = view.querySelector('iframe');
    try {
      iframe.contentWindow.focus();
      iframe.contentWindow.print();
    } catch {
      window.print(); // fallback if the PDF viewer blocks direct printing
    }
  } else if (currentKind === 'docx') {
    window.print();
  }
});
